### ISSUE TITLE
User cannot log in

### ISSUE THREAD

**Issue by bazzel** [bazzel/books#66]
A user is not able to login. When trying to log in, a 500 error occurs.

**Steps to reproduce:**
* Navigate to books.kabisa.nl
* Click Sign in in the top right corner of the page
* Fill in your Kabisa email address and click Sign In

**Expected behaviour:**
A confirmation page should show up and the user receives an email with a URL to continue the process.

**Actual behaviour:**
The following page occurs:

<img width="580" alt="Screenshot 2023-06-21 at 06 58 36" src="https://github.com/kabisa/books/assets/7672/5bac620d-0e84-40f2-b602-4baf35239bff">

This is caused by a missing setting in Sendgrid - when trying to send a mail, sendgrid raises an exception which results in a 500 error:

```
Net::SMTPFatalError (550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements
```

This error can be resolved by following the instructions in the URL mentioned in the error log.

**Comment by sandercamp** [comment]
Fixed this by adding no-reply@kabisa.nl as verified sender to SendGrid. Not sure why this was not the case anymore.
